#include<iostream.h>
#include<conio.h>
void main()
{
clrscr();
int a;
float b;
char c;
long d;
double e;
cout<<"The size of variable of int data type is = "<<sizeof(a);
cout<<"\nThe size of variable of float data type is = "<<sizeof(b);
cout<<"\nThe size of variable of char data type is = "<<sizeof(c);
cout<<"\nThe size of variable of long data type is = "<<sizeof(d);
cout<<"\nThe size of variable of double data type is = "<<sizeof(e);
getch();
}